import { COLOR, type ColorType } from "@/types/index";

export const COLORS: {
	[key in COLOR]: ColorType;
} = {
	[COLOR.ROSEWATER]: {
		colorCode: "#f5e0dc",
		text: "text-ctp-rosewater",
		hoverText: "hover:text-ctp-rosewater",
		focusText: "focus-visible:text-ctp-rosewater",
		background: "bg-ctp-rosewater",
		backgroundGradient: "to-ctp-rosewater/30 dark:to-ctp-rosewater/40",
		hoverBackground: "hover:bg-ctp-rosewater",
		focusBackground: "focus-visible:bg-ctp-rosewater",
		childHoverBackground: "[&>*]:hover:bg-ctp-rosewater/10",
		childFocusBackground: "[&>*]:focus-visible:bg-ctp-rosewater/10",
		outline: "outline-ctp-rosewater",
		hoverOutline: "hover:outline-ctp-rosewater",
		focusOutline: "focus-visible:outline-ctp-rosewater",
		childHoverOutline: "[&>*]:hover:outline-ctp-rosewater/60",
		childFocusOutline: "[&>*]:focus-visible:outline-ctp-rosewater/60",
		scrollColor: "[&::-webkit-scrollbar-thumb]:bg-ctp-rosewater/75",
		toCActiveColor: "group-[.current]:text-ctp-rosewater",
		blogPostColor:
			"[&>hr]:border-[1px] [&>hr]:border-ctp-rosewater/50 dark:[&>hr]:border-ctp-rosewater/75 [&_em]:text-ctp-rosewater [&_strong]:text-ctp-rosewater [&_del]:text-ctp-rosewater [&_a]:text-ctp-rosewater focus-visible:[&_a]:outline-ctp-rosewater [&_blockquote]:border-l-ctp-rosewater [&_dt]:text-ctp-rosewater [&_pre::-webkit-scrollbar]:w-[6px] [&_pre::-webkit-scrollbar]:h-[4px] [&_pre::-webkit-scrollbar-thumb]:rounded-md [&_pre::-webkit-scrollbar-thumb]:bg-ctp-rosewater/75 [&_section]:border-ctp-rosewater/50 dark:[&_section]:border-ctp-rosewater/75 [&_th]:text-ctp-rosewater [&_.remark-code-title]:border-t-ctp-rosewater [&_.remark-code-title]:border-t-2",
		borderColor: "border-ctp-rosewater/50",
	},
	[COLOR.FLAMINGO]: {
		colorCode: "#f2cdcd",
		text: "text-ctp-flamingo",
		hoverText: "hover:text-ctp-flamingo",
		focusText: "focus-visible:text-ctp-flamingo",
		background: "bg-ctp-flamingo",
		backgroundGradient: "to-ctp-flamingo/30 dark:to-ctp-flamingo/40",
		hoverBackground: "hover:bg-ctp-flamingo",
		focusBackground: "focus-visible:bg-ctp-flamingo",
		childHoverBackground: "[&>*]:hover:bg-ctp-flamingo/10",
		childFocusBackground: "[&>*]:focus-visible:bg-ctp-flamingo/10",
		outline: "outline-ctp-flamingo",
		hoverOutline: "hover:outline-ctp-flamingo",
		focusOutline: "focus-visible:outline-ctp-flamingo",
		childHoverOutline: "[&>*]:hover:outline-ctp-flamingo/60",
		childFocusOutline: "[&>*]:focus-visible:outline-ctp-flamingo/60",
		scrollColor: "[&::-webkit-scrollbar-thumb]:bg-ctp-flamingo/75",
		toCActiveColor: "group-[.current]:text-ctp-flamingo",
		blogPostColor:
			"[&>hr]:border-[1px] [&>hr]:border-ctp-flamingo/50 dark:[&>hr]:border-ctp-flamingo/75 [&_em]:text-ctp-flamingo [&_strong]:text-ctp-flamingo [&_del]:text-ctp-flamingo [&_a]:text-ctp-flamingo focus-visible:[&_a]:outline-ctp-flamingo [&_blockquote]:border-l-ctp-flamingo [&_dt]:text-ctp-flamingo [&_pre::-webkit-scrollbar]:w-[6px] [&_pre::-webkit-scrollbar]:h-[4px] [&_pre::-webkit-scrollbar-thumb]:rounded-md [&_pre::-webkit-scrollbar-thumb]:bg-ctp-flamingo/75 [&_section]:border-ctp-flamingo/50 dark:[&_section]:border-ctp-flamingo/75 [&_th]:text-ctp-flamingo [&_.remark-code-title]:border-t-ctp-flamingo [&_.remark-code-title]:border-t-2",
		borderColor: "border-ctp-flamingo/50",
	},
	[COLOR.PINK]: {
		colorCode: "#f5c2e7",
		text: "text-ctp-pink",
		hoverText: "hover:text-ctp-pink",
		focusText: "focus-visible:text-ctp-pink",
		background: "bg-ctp-pink",
		backgroundGradient: "to-ctp-pink/30 dark:to-ctp-pink/40",
		hoverBackground: "hover:bg-ctp-pink",
		focusBackground: "focus-visible:bg-ctp-pink",
		childHoverBackground: "[&>*]:hover:bg-ctp-pink/10",
		childFocusBackground: "[&>*]:focus-visible:bg-ctp-pink/10",
		outline: "outline-ctp-pink",
		hoverOutline: "hover:outline-ctp-pink",
		focusOutline: "focus-visible:outline-ctp-pink",
		childHoverOutline: "[&>*]:hover:outline-ctp-pink/60",
		childFocusOutline: "[&>*]:focus-visible:outline-ctp-pink/60",
		scrollColor: "[&::-webkit-scrollbar-thumb]:bg-ctp-pink/75",
		toCActiveColor: "group-[.current]:text-ctp-pink",
		blogPostColor:
			"[&>hr]:border-[1px] [&>hr]:border-ctp-pink/50 dark:[&>hr]:border-ctp-pink/75 [&_em]:text-ctp-pink [&_strong]:text-ctp-pink [&_del]:text-ctp-pink [&_a]:text-ctp-pink focus-visible:[&_a]:outline-ctp-pink [&_blockquote]:border-l-ctp-pink [&_dt]:text-ctp-pink [&_pre::-webkit-scrollbar]:w-[6px] [&_pre::-webkit-scrollbar]:h-[4px] [&_pre::-webkit-scrollbar-thumb]:rounded-md [&_pre::-webkit-scrollbar-thumb]:bg-ctp-pink/75 [&_section]:border-ctp-pink/50 dark:[&_section]:border-ctp-pink/75 [&_th]:text-ctp-pink [&_.remark-code-title]:border-t-ctp-pink [&_.remark-code-title]:border-t-2",
		borderColor: "border-ctp-pink/50",
	},
	[COLOR.MAUVE]: {
		colorCode: "#cba6f7",
		text: "text-ctp-mauve",
		hoverText: "hover:text-ctp-mauve",
		focusText: "focus-visible:text-ctp-mauve",
		background: "bg-ctp-mauve",
		backgroundGradient: "to-ctp-mauve/30 dark:to-ctp-mauve/40",
		hoverBackground: "hover:bg-ctp-mauve",
		focusBackground: "focus-visible:bg-ctp-mauve",
		childHoverBackground: "[&>*]:hover:bg-ctp-mauve/10",
		childFocusBackground: "[&>*]:focus-visible:bg-ctp-mauve/10",
		outline: "outline-ctp-mauve",
		hoverOutline: "hover:outline-ctp-mauve",
		focusOutline: "focus-visible:outline-ctp-mauve",
		childHoverOutline: "[&>*]:hover:outline-ctp-mauve/60",
		childFocusOutline: "[&>*]:focus-visible:outline-ctp-mauve/60",
		scrollColor: "[&::-webkit-scrollbar-thumb]:bg-ctp-mauve/75",
		toCActiveColor: "group-[.current]:text-ctp-mauve",
		blogPostColor:
			"[&>hr]:border-[1px] [&>hr]:border-ctp-mauve/50 dark:[&>hr]:border-ctp-mauve/75 [&_em]:text-ctp-mauve [&_strong]:text-ctp-mauve [&_del]:text-ctp-mauve [&_a]:text-ctp-mauve focus-visible:[&_a]:outline-ctp-mauve [&_blockquote]:border-l-ctp-mauve [&_dt]:text-ctp-mauve [&_pre::-webkit-scrollbar]:w-[6px] [&_pre::-webkit-scrollbar]:h-[4px] [&_pre::-webkit-scrollbar-thumb]:rounded-md [&_pre::-webkit-scrollbar-thumb]:bg-ctp-mauve/75 [&_section]:border-ctp-mauve/50 dark:[&_section]:border-ctp-mauve/75 [&_th]:text-ctp-mauve [&_.remark-code-title]:border-t-ctp-mauve [&_.remark-code-title]:border-t-2",
		borderColor: "border-ctp-mauve/50",
	},
	[COLOR.RED]: {
		colorCode: "#f38ba8",
		text: "text-ctp-red",
		hoverText: "hover:text-ctp-red",
		focusText: "focus-visible:text-ctp-red",
		background: "bg-ctp-red",
		backgroundGradient: "to-ctp-red/30 dark:to-ctp-red/40",
		hoverBackground: "hover:bg-ctp-red",
		focusBackground: "focus-visible:bg-ctp-red",
		childHoverBackground: "[&>*]:hover:bg-ctp-red/10",
		childFocusBackground: "[&>*]:focus-visible:bg-ctp-red/10",
		outline: "outline-ctp-red",
		hoverOutline: "hover:outline-ctp-red",
		focusOutline: "focus-visible:outline-ctp-red",
		childHoverOutline: "[&>*]:hover:outline-ctp-red/60",
		childFocusOutline: "[&>*]:focus-visible:outline-ctp-red/60",
		scrollColor: "[&::-webkit-scrollbar-thumb]:bg-ctp-red/75",
		toCActiveColor: "group-[.current]:text-ctp-red",
		blogPostColor:
			"[&>hr]:border-[1px] [&>hr]:border-ctp-red/50 dark:[&>hr]:border-ctp-red/75 [&_em]:text-ctp-red [&_strong]:text-ctp-red [&_del]:text-ctp-red [&_a]:text-ctp-red focus-visible:[&_a]:outline-ctp-red [&_blockquote]:border-l-ctp-red [&_dt]:text-ctp-red [&_pre::-webkit-scrollbar]:w-[6px] [&_pre::-webkit-scrollbar]:h-[4px] [&_pre::-webkit-scrollbar-thumb]:rounded-md [&_pre::-webkit-scrollbar-thumb]:bg-ctp-red/75 [&_section]:border-ctp-red/50 dark:[&_section]:border-ctp-red/75 [&_th]:text-ctp-red [&_.remark-code-title]:border-t-ctp-red [&_.remark-code-title]:border-t-2",
		borderColor: "border-ctp-red/50",
	},
	[COLOR.MAROON]: {
		colorCode: "#eba0ac",
		text: "text-ctp-maroon",
		hoverText: "hover:text-ctp-maroon",
		focusText: "focus-visible:text-ctp-maroon",
		background: "bg-ctp-maroon",
		backgroundGradient: "to-ctp-maroon/30 dark:to-ctp-maroon/40",
		hoverBackground: "hover:bg-ctp-maroon",
		focusBackground: "focus-visible:bg-ctp-maroon",
		childHoverBackground: "[&>*]:hover:bg-ctp-maroon/10",
		childFocusBackground: "[&>*]:focus-visible:bg-ctp-maroon/10",
		outline: "outline-ctp-maroon",
		hoverOutline: "hover:outline-ctp-maroon",
		focusOutline: "focus-visible:outline-ctp-maroon",
		childHoverOutline: "[&>*]:hover:outline-ctp-maroon/60",
		childFocusOutline: "[&>*]:focus-visible:outline-ctp-maroon/60",
		scrollColor: "[&::-webkit-scrollbar-thumb]:bg-ctp-maroon/75",
		toCActiveColor: "group-[.current]:text-ctp-maroon",
		blogPostColor:
			"[&>hr]:border-[1px] [&>hr]:border-ctp-maroon/50 dark:[&>hr]:border-ctp-maroon/75 [&_em]:text-ctp-maroon [&_strong]:text-ctp-maroon [&_del]:text-ctp-maroon [&_a]:text-ctp-maroon focus-visible:[&_a]:outline-ctp-maroon [&_blockquote]:border-l-ctp-maroon [&_dt]:text-ctp-maroon [&_pre::-webkit-scrollbar]:w-[6px] [&_pre::-webkit-scrollbar]:h-[4px] [&_pre::-webkit-scrollbar-thumb]:rounded-md [&_pre::-webkit-scrollbar-thumb]:bg-ctp-maroon/75 [&_section]:border-ctp-maroon/50 dark:[&_section]:border-ctp-maroon/75 [&_th]:text-ctp-maroon [&_.remark-code-title]:border-t-ctp-maroon [&_.remark-code-title]:border-t-2",
		borderColor: "border-ctp-maroon/50",
	},
	[COLOR.PEACH]: {
		colorCode: "#fab387",
		text: "text-ctp-peach",
		hoverText: "hover:text-ctp-peach",
		focusText: "focus-visible:text-ctp-peach",
		background: "bg-ctp-peach",
		backgroundGradient: "to-ctp-peach/30 dark:to-ctp-peach/40",
		hoverBackground: "hover:bg-ctp-peach",
		focusBackground: "focus-visible:bg-ctp-peach",
		childHoverBackground: "[&>*]:hover:bg-ctp-peach/10",
		childFocusBackground: "[&>*]:focus-visible:bg-ctp-peach/10",
		outline: "outline-ctp-peach",
		hoverOutline: "hover:outline-ctp-peach",
		focusOutline: "focus-visible:outline-ctp-peach",
		childHoverOutline: "[&>*]:hover:outline-ctp-peach/60",
		childFocusOutline: "[&>*]:focus-visible:outline-ctp-peach/60",
		scrollColor: "[&::-webkit-scrollbar-thumb]:bg-ctp-peach/75",
		toCActiveColor: "group-[.current]:text-ctp-peach",
		blogPostColor:
			"[&>hr]:border-[1px] [&>hr]:border-ctp-peach/50 dark:[&>hr]:border-ctp-peach/75 [&_em]:text-ctp-peach [&_strong]:text-ctp-peach [&_del]:text-ctp-peach [&_a]:text-ctp-peach focus-visible:[&_a]:outline-ctp-peach [&_blockquote]:border-l-ctp-peach [&_dt]:text-ctp-peach [&_pre::-webkit-scrollbar]:w-[6px] [&_pre::-webkit-scrollbar]:h-[4px] [&_pre::-webkit-scrollbar-thumb]:rounded-md [&_pre::-webkit-scrollbar-thumb]:bg-ctp-peach/75 [&_section]:border-ctp-peach/50 dark:[&_section]:border-ctp-peach/75 [&_th]:text-ctp-peach [&_.remark-code-title]:border-t-ctp-peach [&_.remark-code-title]:border-t-2",
		borderColor: "border-ctp-peach/50",
	},
	[COLOR.YELLOW]: {
		colorCode: "#f9e2af",
		text: "text-ctp-yellow",
		hoverText: "hover:text-ctp-yellow",
		focusText: "focus-visible:text-ctp-yellow",
		background: "bg-ctp-yellow",
		backgroundGradient: "to-ctp-yellow/30 dark:to-ctp-yellow/40",
		hoverBackground: "hover:bg-ctp-yellow",
		focusBackground: "focus-visible:bg-ctp-yellow",
		childHoverBackground: "[&>*]:hover:bg-ctp-yellow/10",
		childFocusBackground: "[&>*]:focus-visible:bg-ctp-yellow/10",
		outline: "outline-ctp-yellow",
		hoverOutline: "hover:outline-ctp-yellow",
		focusOutline: "focus-visible:outline-ctp-yellow",
		childHoverOutline: "[&>*]:hover:outline-ctp-yellow/60",
		childFocusOutline: "[&>*]:focus-visible:outline-ctp-yellow/60",
		scrollColor: "[&::-webkit-scrollbar-thumb]:bg-ctp-yellow/75",
		toCActiveColor: "group-[.current]:text-ctp-yellow",
		blogPostColor:
			"[&>hr]:border-[1px] [&>hr]:border-ctp-yellow/50 dark:[&>hr]:border-ctp-yellow/75 [&_em]:text-ctp-yellow [&_strong]:text-ctp-yellow [&_del]:text-ctp-yellow [&_a]:text-ctp-yellow focus-visible:[&_a]:outline-ctp-yellow [&_blockquote]:border-l-ctp-yellow [&_dt]:text-ctp-yellow [&_pre::-webkit-scrollbar]:w-[6px] [&_pre::-webkit-scrollbar]:h-[4px] [&_pre::-webkit-scrollbar-thumb]:rounded-md [&_pre::-webkit-scrollbar-thumb]:bg-ctp-yellow/75 [&_section]:border-ctp-yellow/50 dark:[&_section]:border-ctp-yellow/75 [&_th]:text-ctp-yellow [&_.remark-code-title]:border-t-ctp-yellow [&_.remark-code-title]:border-t-2",
		borderColor: "border-ctp-yellow/50",
	},
	[COLOR.GREEN]: {
		colorCode: "#a6e3a1",
		text: "text-ctp-green",
		hoverText: "hover:text-ctp-green",
		focusText: "focus-visible:text-ctp-green",
		background: "bg-ctp-green",
		backgroundGradient: "to-ctp-green/30 dark:to-ctp-green/40",
		hoverBackground: "hover:bg-ctp-green",
		focusBackground: "focus-visible:bg-ctp-green",
		childHoverBackground: "[&>*]:hover:bg-ctp-green/10",
		childFocusBackground: "[&>*]:focus-visible:bg-ctp-green/10",
		outline: "outline-ctp-green",
		hoverOutline: "hover:outline-ctp-green",
		focusOutline: "focus-visible:outline-ctp-green",
		childHoverOutline: "[&>*]:hover:outline-ctp-green/60",
		childFocusOutline: "[&>*]:focus-visible:outline-ctp-green/60",
		scrollColor: "[&::-webkit-scrollbar-thumb]:bg-ctp-green/75",
		toCActiveColor: "group-[.current]:text-ctp-green",
		blogPostColor:
			"[&>hr]:border-[1px] [&>hr]:border-ctp-green/50 dark:[&>hr]:border-ctp-green/75 [&_em]:text-ctp-green [&_strong]:text-ctp-green [&_del]:text-ctp-green [&_a]:text-ctp-green focus-visible:[&_a]:outline-ctp-green [&_blockquote]:border-l-ctp-green [&_dt]:text-ctp-green [&_pre::-webkit-scrollbar]:w-[6px] [&_pre::-webkit-scrollbar]:h-[4px] [&_pre::-webkit-scrollbar-thumb]:rounded-md [&_pre::-webkit-scrollbar-thumb]:bg-ctp-green/75 [&_section]:border-ctp-green/50 dark:[&_section]:border-ctp-green/75 [&_th]:text-ctp-green [&_.remark-code-title]:border-t-ctp-green [&_.remark-code-title]:border-t-2",
		borderColor: "border-ctp-green/50",
	},
	[COLOR.TEAL]: {
		colorCode: "#94e2d5",
		text: "text-ctp-teal",
		hoverText: "hover:text-ctp-teal",
		focusText: "focus-visible:text-ctp-teal",
		background: "bg-ctp-teal",
		backgroundGradient: "to-ctp-teal/30 dark:to-ctp-teal/40",
		hoverBackground: "hover:bg-ctp-teal",
		focusBackground: "focus-visible:bg-ctp-teal",
		childHoverBackground: "[&>*]:hover:bg-ctp-teal/10",
		childFocusBackground: "[&>*]:focus-visible:bg-ctp-teal/10",
		outline: "outline-ctp-teal",
		hoverOutline: "hover:outline-ctp-teal",
		focusOutline: "focus-visible:outline-ctp-teal",
		childHoverOutline: "[&>*]:hover:outline-ctp-teal/60",
		childFocusOutline: "[&>*]:focus-visible:outline-ctp-teal/60",
		scrollColor: "[&::-webkit-scrollbar-thumb]:bg-ctp-teal/75",
		toCActiveColor: "group-[.current]:text-ctp-teal",
		blogPostColor:
			"[&>hr]:border-[1px] [&>hr]:border-ctp-teal/50 dark:[&>hr]:border-ctp-teal/75 [&_em]:text-ctp-teal [&_strong]:text-ctp-teal [&_del]:text-ctp-teal [&_a]:text-ctp-teal focus-visible:[&_a]:outline-ctp-teal [&_blockquote]:border-l-ctp-teal [&_dt]:text-ctp-teal [&_pre::-webkit-scrollbar]:w-[6px] [&_pre::-webkit-scrollbar]:h-[4px] [&_pre::-webkit-scrollbar-thumb]:rounded-md [&_pre::-webkit-scrollbar-thumb]:bg-ctp-teal/75 [&_section]:border-ctp-teal/50 dark:[&_section]:border-ctp-teal/75 [&_th]:text-ctp-teal [&_.remark-code-title]:border-t-ctp-teal [&_.remark-code-title]:border-t-2",
		borderColor: "border-ctp-teal/50",
	},
	[COLOR.SKY]: {
		colorCode: "#89dceb",
		text: "text-ctp-sky",
		hoverText: "hover:text-ctp-sky",
		focusText: "focus-visible:text-ctp-sky",
		background: "bg-ctp-sky",
		backgroundGradient: "to-ctp-sky/30 dark:to-ctp-sky/40",
		hoverBackground: "hover:bg-ctp-sky",
		focusBackground: "focus-visible:bg-ctp-sky",
		childHoverBackground: "[&>*]:hover:bg-ctp-sky/10",
		childFocusBackground: "[&>*]:focus-visible:bg-ctp-sky/10",
		outline: "outline-ctp-sky",
		hoverOutline: "hover:outline-ctp-sky",
		focusOutline: "focus-visible:outline-ctp-sky",
		childHoverOutline: "[&>*]:hover:outline-ctp-sky/60",
		childFocusOutline: "[&>*]:focus-visible:outline-ctp-sky/60",
		scrollColor: "[&::-webkit-scrollbar-thumb]:bg-ctp-sky/75",
		toCActiveColor: "group-[.current]:text-ctp-sky",
		blogPostColor:
			"[&>hr]:border-[1px] [&>hr]:border-ctp-sky/50 dark:[&>hr]:border-ctp-sky/75 [&_em]:text-ctp-sky [&_strong]:text-ctp-sky [&_del]:text-ctp-sky [&_a]:text-ctp-sky focus-visible:[&_a]:outline-ctp-sky [&_blockquote]:border-l-ctp-sky [&_dt]:text-ctp-sky [&_pre::-webkit-scrollbar]:w-[6px] [&_pre::-webkit-scrollbar]:h-[4px] [&_pre::-webkit-scrollbar-thumb]:rounded-md [&_pre::-webkit-scrollbar-thumb]:bg-ctp-sky/75 [&_section]:border-ctp-sky/50 dark:[&_section]:border-ctp-sky/75 [&_th]:text-ctp-sky [&_.remark-code-title]:border-t-ctp-sky [&_.remark-code-title]:border-t-2",
		borderColor: "border-ctp-sky/50",
	},
	[COLOR.SAPPHIRE]: {
		colorCode: "#74c7ec",
		text: "text-ctp-sapphire",
		hoverText: "hover:text-ctp-sapphire",
		focusText: "focus-visible:text-ctp-sapphire",
		background: "bg-ctp-sapphire",
		backgroundGradient: "to-ctp-sapphire/30 dark:to-ctp-sapphire/40",
		hoverBackground: "hover:bg-ctp-sapphire",
		focusBackground: "focus-visible:bg-ctp-sapphire",
		childHoverBackground: "[&>*]:hover:bg-ctp-sapphire/10",
		childFocusBackground: "[&>*]:focus-visible:bg-ctp-sapphire/10",
		outline: "outline-ctp-sapphire",
		hoverOutline: "hover:outline-ctp-sapphire",
		focusOutline: "focus-visible:outline-ctp-sapphire",
		childHoverOutline: "[&>*]:hover:outline-ctp-sapphire/60",
		childFocusOutline: "[&>*]:focus-visible:outline-ctp-sapphire/60",
		scrollColor: "[&::-webkit-scrollbar-thumb]:bg-ctp-sapphire/75",
		toCActiveColor: "group-[.current]:text-ctp-sapphire",
		blogPostColor:
			"[&>hr]:border-[1px] [&>hr]:border-ctp-sapphire/50 dark:[&>hr]:border-ctp-sapphire/75 [&_em]:text-ctp-sapphire [&_strong]:text-ctp-sapphire [&_del]:text-ctp-sapphire [&_a]:text-ctp-sapphire focus-visible:[&_a]:outline-ctp-sapphire [&_blockquote]:border-l-ctp-sapphire [&_dt]:text-ctp-sapphire [&_pre::-webkit-scrollbar]:w-[6px] [&_pre::-webkit-scrollbar]:h-[4px] [&_pre::-webkit-scrollbar-thumb]:rounded-md [&_pre::-webkit-scrollbar-thumb]:bg-ctp-sapphire/75 [&_section]:border-ctp-sapphire/50 dark:[&_section]:border-ctp-sapphire/75 [&_th]:text-ctp-sapphire [&_.remark-code-title]:border-t-ctp-sapphire [&_.remark-code-title]:border-t-2",
		borderColor: "border-ctp-sapphire/50",
	},
	[COLOR.BLUE]: {
		colorCode: "#89b4fa",
		text: "text-ctp-blue",
		hoverText: "hover:text-ctp-blue",
		focusText: "focus-visible:text-ctp-blue",
		background: "bg-ctp-blue",
		backgroundGradient: "to-ctp-blue/30 dark:to-ctp-blue/40",
		hoverBackground: "hover:bg-ctp-blue",
		focusBackground: "focus-visible:bg-ctp-blue",
		childHoverBackground: "[&>*]:hover:bg-ctp-blue/10",
		childFocusBackground: "[&>*]:focus-visible:bg-ctp-blue/10",
		outline: "outline-ctp-blue",
		hoverOutline: "hover:outline-ctp-blue",
		focusOutline: "focus-visible:outline-ctp-blue",
		childHoverOutline: "[&>*]:hover:outline-ctp-blue/60",
		childFocusOutline: "[&>*]:focus-visible:outline-ctp-blue/60",
		scrollColor: "[&::-webkit-scrollbar-thumb]:bg-ctp-blue/75",
		toCActiveColor: "group-[.current]:text-ctp-blue",
		blogPostColor:
			"[&>hr]:border-[1px] [&>hr]:border-ctp-blue/50 dark:[&>hr]:border-ctp-blue/75 [&_em]:text-ctp-blue [&_strong]:text-ctp-blue [&_del]:text-ctp-blue [&_a]:text-ctp-blue focus-visible:[&_a]:outline-ctp-blue [&_blockquote]:border-l-ctp-blue [&_dt]:text-ctp-blue [&_pre::-webkit-scrollbar]:w-[6px] [&_pre::-webkit-scrollbar]:h-[4px] [&_pre::-webkit-scrollbar-thumb]:rounded-md [&_pre::-webkit-scrollbar-thumb]:bg-ctp-blue/75 [&_section]:border-ctp-blue/50 dark:[&_section]:border-ctp-blue/75 [&_th]:text-ctp-blue [&_.remark-code-title]:border-t-ctp-blue [&_.remark-code-title]:border-t-2",
		borderColor: "border-ctp-blue/50",
	},
	[COLOR.LAVENDER]: {
		colorCode: "#b4befe",
		text: "text-ctp-lavender",
		hoverText: "hover:text-ctp-lavender",
		focusText: "focus-visible:text-ctp-lavender",
		background: "bg-ctp-lavender",
		backgroundGradient: "to-ctp-lavender/30 dark:to-ctp-lavender/40",
		hoverBackground: "hover:bg-ctp-lavender",
		focusBackground: "focus-visible:bg-ctp-lavender",
		childHoverBackground: "[&>*]:hover:bg-ctp-lavender/10",
		childFocusBackground: "[&>*]:focus-visible:bg-ctp-lavender/10",
		outline: "outline-ctp-lavender",
		hoverOutline: "hover:outline-ctp-lavender",
		focusOutline: "focus-visible:outline-ctp-lavender",
		childHoverOutline: "[&>*]:hover:outline-ctp-lavender/60",
		childFocusOutline: "[&>*]:focus-visible:outline-ctp-lavender/60",
		scrollColor: "[&::-webkit-scrollbar-thumb]:bg-ctp-lavender/75",
		toCActiveColor: "group-[.current]:text-ctp-lavender",
		blogPostColor:
			"[&>hr]:border-[1px] [&>hr]:border-ctp-lavender/50 dark:[&>hr]:border-ctp-lavender/75 [&_em]:text-ctp-lavender [&_strong]:text-ctp-lavender [&_del]:text-ctp-lavender [&_a]:text-ctp-lavender focus-visible:[&_a]:outline-ctp-lavender [&_blockquote]:border-l-ctp-lavender [&_dt]:text-ctp-lavender [&_pre::-webkit-scrollbar]:w-[6px] [&_pre::-webkit-scrollbar]:h-[4px] [&_pre::-webkit-scrollbar-thumb]:rounded-md [&_pre::-webkit-scrollbar-thumb]:bg-ctp-lavender/75 [&_section]:border-ctp-lavender/50 dark:[&_section]:border-ctp-lavender/75 [&_th]:text-ctp-lavender [&_.remark-code-title]:border-t-ctp-lavender [&_.remark-code-title]:border-t-2",
		borderColor: "border-ctp-lavender/50",
	},
};
